config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true,
    length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title= 'About Us';
        @content =' This is about page';
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts =Post.all

    end
    def show
        @post =Post.find(params[:id])
    end

    def new
        @post=Post.new

    end
    def create
        #render plain: params[ :post].inspect
        @post = Post.new(post_params)

        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    def edit
        @post =Post.find(params[:id])

    end
    def update
        @post =Post.find(params[:id])
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end

    end
    def destroy
        @post =Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private def post_params
        params.require(:post).permit(:title, :body)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudApp</title>
    
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body style="background-color: #696969">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  
  <%= link_to "CrudApp", home_path,
                        :class => 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <span style="color: grey">
      <%= link_to "Home", home_path,
                        :class => 'nav-link' %></span>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
    <button class="btn btn-outline-warning my-2 my-sm-0" type="submit"><%= link_to "Create Post", new_post_path,
                                                                                          :class => 'nav-link' %></button>
    
    </form>
  </div>
</nav>
<br><br><br><br>



  
<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1><span style="color:orange;font-weight:bold">Edit Post</span></h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %><br>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
    <span style="color:white"><%= f.label :title %></span><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
    <span style="color:white"> <%= f.label :body %></span><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class =>'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1>     </h1>
<% @posts.each do |post| %>
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0" >
          <h3 class="display-4 font-italic"><%= post.title %></h3>
          <p class="lead my-3"><p><%= post.body %></p></p>
          <p class="lead mb-0"><%= link_to "Continue Reading...", post_path(post) %></p>
        </div>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %><br>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class =>'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
                    <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
                    <div class="col-md-6 px-0" >
                      <h3 class="display-4 font-italic"><%= @post.title %></h3>
                      <p class="lead my-3"><p><%= @post.body %></p></p>
                      <hr>
                      
                    </div>
                    
            </div>
            <%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-primary' %>
                    <%= link_to "Delete", post_path(@post), 
                                        method: :delete,
                                        data: {confirm: 'Are you sure?'},
                                        :class => 'btn btn-danger' %>